name: Polaris-FE CI/CD

on:
  push:
    paths:
      - "Polaris-FE/**"
  pull_request:
    branches:
      - testing-main-do-not-push
    paths:
      - "Polaris-FE/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
      - name: Install modules
        run: cd Polaris-FE && npm i
      - name: Run Test Suite
        run: cd Polaris-FE && npm run test:ci
      - name: Run Linter
        run: cd Polaris-FE && npm run lint
      - name: Check Code Formatting
        run: cd Polaris-FE && npm run format:check
      - name: Run Jest with Coverage
        run: |
          cd Polaris-FE
          npm run test:coverage
      - name: Debug Coverage File
        run: ls -l Polaris-FE/coverage
      - name: Upload lcov.info file
        uses: actions/upload-artifact@v4
        with:
          name: lcov-info
          path: Polaris-FE/coverage/lcov.info

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Download lcov.info file
        uses: actions/download-artifact@v4
        with:
          name: lcov-info
      - name: Debug Downloaded Artifact
        run: ls -l
      # - name: Move lcov.info to SonarQube expected path
      #   run: mv ./coverage/lcov.info ./
      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        run: |
          cd Polaris-FE
          npx sonarqube-scanner \
            -Dsonar.projectKey=390MiniCapstone_Polaris \
            -Dsonar.organization=390minicapstone \
            -Dsonar.sources=. \
            -Dsonar.exclusions=node_modules/**,dist/**,build/** \
            -Dsonar.javascript.lcov.reportPaths=lcov.info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
